- name: Deploy la-casa-del-aire to SFTP server
 uses: wlixcc/SFTP-Deploy-Action@v1.2.6
 with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          local_path: "./la-casa-del-aire/*"
          remote_path: "/clickandbuilds/Casadelaire"
          sftp_only: true
          delete_remote_files: true
          exclude: |
            assets/**
            .github/**
            node_modules/**
            .gitignore
            package.json
            package-lock.json
            README.md
